import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { ReactQueryProvider } from "@/components/providers/react-query-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body>
        <ReactQueryProvider>
          <NuqsAdapter>
            <main className="min-h-screen w-full bg-background text-foreground">
              {children}
            </main>
          </NuqsAdapter>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
