name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-build:
    name: Lint, Type-check & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Check TypeScript types
        run: pnpm tsc --noEmit

      - name: Run ESLint
        run: pnpm lint

      - name: Check code formatting
        run: pnpm format:check

      - name: Build application
        run: pnpm build
        env:
          # Variables d'environnement nécessaires pour le build
          DATABASE_URL: file:./dev.db
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          BETTER_AUTH_URL: http://localhost:3000
          USESEND_API_KEY: test-api-key

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint-and-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Setup database
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: file:./test.db

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          DATABASE_URL: file:./test.db
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          BETTER_AUTH_URL: http://localhost:3000
          USESEND_API_KEY: test-api-key

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
